### ISSUE TITLE
issue running the script

### ISSUE THREAD

**Issue by pericp** [routetehpacketz/cisco-ip-trace#1]
Traceback (most recent call last):
  File "iptrace.py", line 223, in <module>
    main()
  File "iptrace.py", line 219, in main
    singleip_scan()
  File "iptrace.py", line 202, in singleip_scan
    cdp_nei_ip,match_mac=core(core_router,current_ip)
  File "iptrace.py", line 89, in core
    mac_port=mac_port.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by routetehpacketz** [comment]
Hey percip,

It appears the interface names on your core router do not match the regex I'm using. Can you tell me what model of device this is, how the interfaces are named, and if you're using port-channels?

**Comment by pericp** [comment]
Hello,

Thanks for the quick reply. I am using Cisco 4510 switches and Cisco 4321 router to test the script.

**Comment by pericp** [comment]
Also, I do have portchannels.

**Comment by routetehpacketz** [comment]
I believe the error is due to the script starting on an actual IOS router and not a L3 switch. to be honest I just haven't tested it in this scenario. I'll put it on my to-do list and test it out tomorrow. thanks for bringing this to my attention!

**Comment by routetehpacketz** [comment]
hey percip,

I just wanted to update you on where this issue stands. I found I just need to implement functionality to determine if the MAC is being learned on a routed port. This requires a little bit of re-design, so I appreciate your patience while I get this fixed. I'll comment again when I have it working.

**Comment by routetehpacketz** [comment]
hey again percip,

I've made some changes to the script to accommodate routed ports. can you see if it's working for you now?
