### ISSUE TITLE
Script dies when not able to ssh into end device -  make it skip that device and continue? 

### ISSUE THREAD

**Issue by net9000** [routetehpacketz/cisco-ip-trace#12]
Ran into another issue where the script just stops when it can't login to a device that it finds has the MAC address it is attempting to locate.  In this case a user has a computer daisy chained from their IP phone.  Obviously it's not a switch but I would like the script to keep going rather than stopping.  In a case like this can some logic be added to tell it to continue on?  

```
Tracing 10.99.16.94...Traceback (most recent call last):
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cisco-ip-trace-dns.py", line 326, in <module>
    main()
  File "cisco-ip-trace-dns.py", line 317, in main
    line = TraceIPAddress(ipaddress_ipcalc)
  File "cisco-ip-trace-dns.py", line 284, in TraceIPAddress
    line=TraceMac(mac, ipaddress, dns_name, core_switch, username, password)
  File "cisco-ip-trace-dns.py", line 236, in TraceMac
    line=TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password)
  File "cisco-ip-trace-dns.py", line 236, in TraceMac
    line=TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password)
  File "cisco-ip-trace-dns.py", line 220, in TraceMac
    next_switch_conn=ConnectHandler(device_type='cisco_ios',host=switch_ip,username=username,password=password)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.99.29.196:22
```
In the above the last IP is a phone 10.99.29.196 and the IP 10.99.16.93 is hanging off of that phone.

**Comment by routetehpacketz** [comment]
Hey @net9000,

Handling for IP phones shouldn't be too difficult as a previous contributor already added similar handling for Cisco access points. Are you using Cisco phones in your org?

**Comment by net9000** [comment]
I think you misunderstood me.  The MAC it found is hanging off a phone (via a port on the back of thep  hone) so the script is trying to ssh into the phone to find the port the MAC is coming out and at that point the script breaks.  

`Connection to device timed-out: cisco_ios 10.99.29.196:22`

That is the script trying to SSH into the phone.  Make sense?

**Comment by routetehpacketz** [comment]
I do understand the script is trying to SSH into phone. This is because it is learning the phone's IP via CDP neighbor.

I plan to add handling for SSH failures, but it is still useful to know what CDP data is being received to ensure the accuracy of the info the script outputs.

**Comment by net9000** [comment]
Hi any movement on this issue?  This specific problem brings the script to halt when it can't ssh into whatever device the MAC is hanging off of.  It would be nice to just skip it and keep going and report back with failures rather than stopping altogether.  It becomes slow and laborious when it happens.

**Comment by routetehpacketz** [comment]
Hey, @net9000 

Sorry for the delay. This is the issue I am going to work on next. I may have to have it simply skip when a Cisco IP phone is detected as the script currently does with Cisco access points, but I will only do that if I do not find an easy way of ending the current trace if the script cannot SSH to a CDP neighbor. I will create a pull request for this issue now.

**Comment by routetehpacketz** [comment]
Hey, @net9000 

Try [this](https://github.com/routetehpacketz/cisco-ip-trace/blob/pr/ssh_fail_phone/cisco_ip_trace.py) as in a few scenarios. Currently it just bypasses when the string "SEP" is found in a CDP neighbor detail output. This sufficed previously for "AIR" to bypass access points. 

I am still going to work on better handling for SSH failures, but this may help with the problem you're facing now with PCs daisy-chained off of IP phones.

**Comment by routetehpacketz** [comment]
hey again, @net9000 

I just wanted to follow up to see how testing has gone with the simple bypass for Cisco phones.

**Comment by net9000** [comment]
@routetehpacketz running it now but its painfully slow, but it seems to have made it past the phone issue.  Is there anyway to speed it up?   Also can we make it so it references a txt or csv file made up of a list of IPs?  For instance I know I am not using an entire /24 so I don't want to wait around for it to scan the entire CIDR.  I want it to just scan what is in the ARP table and nothing else.  It would cut down on the time and only return relevant data.

**Comment by net9000** [comment]
@routetehpacketz One issue I ran into with the ouptut to CSV.  It seems that when there is no reverse DNS lookup it puts the 'switch' data into the MAC address field and the MAC into the Reverse DNS Name column.  Its odd.  Not sure if its because I am outputing to a CSV vs TXT file, any idea? 


```
Device IP | Reverse DNS Name | MAC Address | Switch | Port | Port Description | Interface Type | VLANs on port | Port MAC count
-- | -- | -- | -- | -- | -- | -- | -- | --
10.103.16.1 | 00b6.70b2.91d6 | r1-xxx-xx | Unknown |   |   |   |   |  
10.103.16.20 | N/A | 000c.29ad.6c5a | sw-xxx-xx | Gi2/0/22 |   | access | 16 | 7
```

**Comment by net9000** [comment]
![image](https://user-images.githubusercontent.com/44323168/80410018-db5d8580-8897-11ea-92a9-383eb8520eff.png)

**Comment by routetehpacketz** [comment]
Hey @net9000,

Thanks for taking the time to test this. There's definitely something up with the output of the CSV. Let me take a look and get back to you.

As far as speed, I know the script isn't the fastest, but part of the reason is unfortunately necessary due to how `netmiko` works. It needs to add a delay each time it runs an SSH command in order for to ensure it receives all of the responding data before moving onto the next step. 

I will still see what can be done to speed of the script overall. One idea I had was to see if I could leverage Python's `multiprocessing` module to run multiple tasks against sections of the supplied CIDR range, but this may take some time.

Just curious, how many switch hops deep are some of the IPs you are tracing?

**Comment by net9000** [comment]
1 or 2 at most as we use a core/distro > access layer across our environment.

**Comment by routetehpacketz** [comment]
Hey again, @net9000 

I think I found the cause of the CSV getting screwed up. Did you run this against switches with TenGigabit interfaces?

If so, please try [this latest commit](https://github.com/routetehpacketz/cisco-ip-trace/blob/fe6f2444d4170eb87a470a50e21495d318abf102/cisco_ip_trace.py).

**Comment by net9000** [comment]
@routetehpacketz

Latest iteration doesn't work:

```
sudo ./enable-v4.py
  File "./enable-v4.py", line 289
    print("\nTracing " + ipaddress + "...", end="") 
```

**Comment by net9000** [comment]
@routetehpacketz Just wondering if you had a chance to look why the new revision isn't working?  I tried to figure it out but it looks like the only thing that changed was the `int_regex = `.

**Comment by net9000** [comment]
@routetehpacketz looks like the latest iteration is trying to SSH into APs:

```
Tracing 10.13.5.20...Traceback (most recent call last):
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./enable-v4.py", line 347, in <module>
    main()
  File "./enable-v4.py", line 337, in main
    line = TraceIPAddress(ipaddress_ipcalc)
  File "./enable-v4.py", line 304, in TraceIPAddress
    line = TraceMac(mac, ipaddress, dns_name, core_switch, username, password, secret)
  File "./enable-v4.py", line 254, in TraceMac
    line = TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password, secret)
  File "./enable-v4.py", line 254, in TraceMac
    line = TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password, secret)
  File "./enable-v4.py", line 238, in TraceMac
    secret=secret)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.103.5.20:22
```

**Comment by net9000** [comment]
Still doing some weird stuff, this time trying to ssh into IPs that aren't even in use. 
```
Tracing 10.102.17.122...Traceback (most recent call last):
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./enable-v4.py", line 347, in <module>
    main()
  File "./enable-v4.py", line 337, in main
    line = TraceIPAddress(ipaddress_ipcalc)
  File "./enable-v4.py", line 304, in TraceIPAddress
    line = TraceMac(mac, ipaddress, dns_name, core_switch, username, password, secret)
  File "./enable-v4.py", line 254, in TraceMac
    line = TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password, secret)
  File "./enable-v4.py", line 238, in TraceMac
    secret=secret)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 192.168.1.50:22
```
I don't understand this because that IP 10.102.17.122 and MAC 2c3e.cf7a.b389 are local to the device that is logging into:
```
r1#show arp | i 10.102.17.122
Internet  10.102.17.122          20   2c3e.cf7a.b389  ARPA   Vlan17
r1#show mac address-table | i b389
  17    2c3e.cf7a.b389    DYNAMIC     Gi1/0/17
```

But for whatever reason its trying to ssh to a 192.168.1.50 IP which isn't even a CIDR on this network.  Can you shed some light on what is happening here?

**Comment by routetehpacketz** [comment]
Hey @net9000,

Sorry for the delayed response! I think it was how I appended `SEP` to the existing regex for detecting Cisco APs. Let me get back at this and I will comment with the latest link to test again.

**Comment by net9000** [comment]
@routetehpacketz 

Were you able to figure this out?  I really want to keep using this but the time it takes to rerun it when this happens and for entire subnets is almost making it not worth it to me.

**Comment by routetehpacketz** [comment]
hey @net9000,

I appreciate your patience on these requests. Overall they have me thinking of ways to enhance the script. I am still working full-time so I am not always setting aside time for this.

Let me correct this regex issue first and will look into both the full ARP scan and input file scan next.

**Comment by routetehpacketz** [comment]
okay try this [latest commit](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/9b7e36132a77dcbec241d2541053a0bd430eb2a2/cisco_ip_trace.py)

**Comment by net9000** [comment]
@routetehpacketz 

Failing again and not sure why...in this example 10.105.5.50 is an access point on a switch connected via 10g to the core. That switch (2960X) does not require an enable password as the account has level 15 privilege.   Why is it trying to ssh into an access point IP?  All the devices on this network are APs as well and .50 is the first non-gateway IP in use and the script dies right there.    

```
Tracing 10.105.5.50...Traceback (most recent call last):
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/local-dp/p3-env/lib/python3.6/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./enable-v5.py", line 346, in <module>
    main()
  File "./enable-v5.py", line 336, in main
    line = TraceIPAddress(ipaddress_ipcalc)
  File "./enable-v5.py", line 303, in TraceIPAddress
    line = TraceMac(mac, ipaddress, dns_name, core_switch, username, password, secret)
  File "./enable-v5.py", line 253, in TraceMac
    line = TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password, secret)
  File "./enable-v5.py", line 253, in TraceMac
    line = TraceMac(mac, device_ip, dns_name, cdp_nei_ip, username, password, secret)
  File "./enable-v5.py", line 237, in TraceMac
    secret=secret)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.105.5.50:22
```

**Comment by routetehpacketz** [comment]
what is the output of **show cdp neighbor** on that port going to the access point?

**Comment by net9000** [comment]
@routetehpacketz 

```
2960#show cdp neighbors gi1/0/38
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater, P - Phone,
                  D - Remote, C - CVTA, M - Two-port Mac Relay

Device ID        Local Intrfce     Holdtme    Capability  Platform  Port ID
e0cbbc92720d     Gig 1/0/38        158              R S   Meraki MR Port 0

```

**Comment by routetehpacketz** [comment]
ah it's a Meraki. sorry, can you give me **show cdp neighbor detail**? feel free to substitute any info you don't want exposed, but please include the device model as it is.

**Comment by net9000** [comment]
@routetehpacketz 

```
Device ID: e0cbbc92720d
Entry address(es):
  IP address: 10.195.5.50
Platform: Meraki MR42 Cloud Managed AP,  Capabilities: Router Switch
Interface: GigabitEthernet1/0/38,  Port ID (outgoing port): Port 0
Holdtime : 114 sec

Version :
1

advertisement version: 2
Power drawn: 20.000 Watts
Power request id: 37473, Power management id: 6
Power request levels are:20000 0 0 0 0
```

**Comment by routetehpacketz** [comment]
hey @net9000 

Thanks for providing the info. I have changed the script to use Python's built-in error handling to bypass CDP neighbor IPs it cannot SSH into. Please try the latest [here](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/26309897eb7a615f5a08acb012d4840749224501/cisco_ip_trace.py).

**Comment by net9000** [comment]
@routetehpacketz 

Looks promising:  

```
Tracing 10.105.5.50...error:
```

Traced to CDP neighbor 10.105.5.50, but could not SSH into it.

Device IP,Reverse DNS Name,MAC Address,Switch,Port,Port Description,Interface Type,VLANs on port,Port MAC count
10.195.5.50,ap26-e0cbbc92720d,e0cb.bc92.720d,2960,Gi1/0/38,### APs###,trunk,"5,20,22",1
```
```

**Comment by routetehpacketz** [comment]
hey @net9000,

Happy Monday! I'm glad to hear it is working so far. If you don't mind running a few tests today to confirm and commenting again I would appreciate it. Once comfortable enough to call this one resolved, I'll merge the related pull request and get cracking on your other requests.

**Comment by net9000** [comment]
@routetehpacketz 

Looks like its working as expected now.  It was able to discover the APs without issue.
