### ISSUE TITLE
no input password

### ISSUE THREAD

**Issue by lendsham** [routetehpacketz/cisco-ip-trace#19]
Hi, 

After i input username, then should i waiting or what?, because no pop up to input password or anything.
I've waited for 5 minutes but nothing happen

![image](https://user-images.githubusercontent.com/19310986/85774653-a2377980-b751-11ea-86c4-c8f1cab586b3.png)

**Comment by routetehpacketz** [comment]
hey @lendsham, I cannot reproduce this issue running the script on either Windows 10 or Ubuntu. Can you test from another computer?

**Comment by routetehpacketz** [comment]
@lendsham

**Comment by routetehpacketz** [comment]
@lendsham 

any response from you on this?
