### ISSUE TITLE
Always shows No mac for the IP

### ISSUE THREAD

**Issue by VijayShenthil** [routetehpacketz/cisco-ip-trace#2]
I use 2960x and when I manually ping or find IP, I can do the arp. when I run script, it says, No MAC for x.x.x.x Not sure what is happening

**Comment by routetehpacketz** [comment]
hey Vijay, can you show me the output of the "show ip arp [IP]" and "show mac address-table address [MAC]" commands?

**Comment by VijayShenthil** [comment]
Switch>s ip arp 10.38.91.198
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.38.91.198           45   34e6.d758.d20b  ARPA   Vlan90
Switch>sh mac ad ad 34e6.d758.d20b
          Mac Address Table
-------------------------------------------

Vlan    Mac Address       Type        Ports
----    -----------       --------    -----
  90    34e6.d758.d20b    DYNAMIC     Fa1/0/26
Total Mac Addresses for this criterion: 1

**Comment by VijayShenthil** [comment]
GetPassWarning: Can not control echo on the terminal.
Warning: Password input may be echoed.
Password: xxxxx

No MAC for 10.38.91.198

>>>

**Comment by VijayShenthil** [comment]
Switch>s ip arp 10.38.91.198
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.38.91.198           45   34e6.d758.d20b  ARPA   Vlan90
Switch>sh mac ad ad 34e6.d758.d20b
          Mac Address Table
-------------------------------------------

Vlan    Mac Address       Type        Ports
----    -----------       --------    -----
  90    34e6.d758.d20b    DYNAMIC     Fa1/0/26
Total Mac Addresses for this criterion: 1

**Comment by routetehpacketz** [comment]
Hi Vijay, I believe you are getting this message because you are not in enabled mode, so the "show cdp neighbor" command cannot run. This is due to an oversight on my part as I have not accommodated the need for entering an enable password within the script. I will add this to my list of to-dos.

Can you change your config to put you in enable mode automatically?

line vty 0 15
privi lev 15

Then try running the script again and let me know the result.

**Comment by VijayShenthil** [comment]
Hello, I'm able to run 'sh cdp nei' when not in enable mode.. I tried all the commands that is used in the script without enable mode.. All works fine.. I dont think it is issue with enable mode.  and if i go logically, this script terminates before executing 'sh cdp nei'.. It is going to check only ping and sh ip arp

**Comment by VijayShenthil** [comment]
anything else I need to check ?

**Comment by routetehpacketz** [comment]
thanks for the compliment! :smile: 

It appears that the script is failing the regex search against the `show ip arp "+current_ip+" | inc "+current_ip`, but the output of that command when you run it manually looks as expected.

You mentioned you were doing this on a 2960x, but the output of your `show mac ad ad` shows a FastEthernet interface. what exact model switch is it?

Also, can you ensure you are running Python 3.x and that all of the modules the script uses are up-to-date?

**Comment by VijayShenthil** [comment]
Yes.. you are correct.. The output I have pasted is from 3750, I tried in 9300, 2960x and another switch which has priv 15 in vty 0 15. Same error for all. Even when I run for range, for complete range, No mac for IP is the result.

**Comment by routetehpacketz** [comment]
hey again Vijay,

I'm reading over your output examples and the script and am a bit stumped as to why it's failing. I created the attached debug.py script which has some extra print statements that may help diagnose the reason it's failing for you.

Can you run the debug.py and reply with the output in a text file? Remove any sensitive info from the output if needed.

[debug.py.txt](https://github.com/routetehpacketz/cisco-ip-trace/files/3195848/debug.py.txt)

**Comment by VijayShenthil** [comment]
Traceback (most recent call last):
  File "C:\Users\Shentv\Downloads\debug.py", line 261, in <module>
    main()
  File "C:\Users\Shentv\Downloads\debug.py", line 257, in main
    singleip_scan()
  File "C:\Users\Shentv\Downloads\debug.py", line 240, in singleip_scan
    cdp_nei_ip,match_mac=core(core_router,current_ip)
  File "C:\Users\Shentv\Downloads\debug.py", line 69, in core
    print('Line 69\n\n'+match_mac.group()+'\n\n')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by VijayShenthil** [comment]
GetPassWarning: Can not control echo on the terminal.
Warning: Password input may be echoed.
Password: 
Line 67


switch>term len 0
switch>ping 10.44.149.109 


Traceback (most recent call last):
  File "C:\Users\Shentv\Downloads\debug.py", line 261, in <module>
    main()
  File "C:\Users\Shentv\Downloads\debug.py", line 257, in main
    singleip_scan()
  File "C:\Users\Shentv\Downloads\debug.py", line 240, in singleip_scan
    cdp_nei_ip,match_mac=core(core_router,current_ip)
  File "C:\Users\Shentv\Downloads\debug.py", line 69, in core
    print('Line 69\n\n'+match_mac.group(1)+'\n\n')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by VijayShenthil** [comment]
Found the issue.. It was nothing to do with Code.. Increased sleep to 5 and it works..

**Comment by routetehpacketz** [comment]
ahh that's good to know. I have had plans to change the script from using paramiko to netmiko since it better accommodates this sort of thing. I'll add it to my list of to-dos as well.

thanks for testing for me and being so patient!

**Comment by VijayShenthil** [comment]
Thank you as well.  Happy Scripting :)

**Comment by routetehpacketz** [comment]
hey again, Vijay!

I spent some time migrating the script from paramiko to netmiko since it has better handling for waiting for devices to respond before moving onto the next command.

Want to download the latest revision and see if it runs successfully for you?

Thanks!

**Comment by routetehpacketz** [comment]
hey Vijay,

I just wanted to check in once again if you wouldn't mind testing the new script for me. I wanted to confirm it ran successfully for you without needing any alterations.

**Comment by robschn** [comment]
Hi routetehpacketz,

I downloaded the script and have been running it for the last hour, so I can confirm everything is working on netmiko.

**Comment by routetehpacketz** [comment]
thanks, Robert! I believe with netmiko the script will now accommodate varying response times as it waits for the prompt to return before running the next command. I will mark this issue closed once again.
