### ISSUE TITLE
Not related to this

### ISSUE THREAD

**Issue by technologyevangelist1** [routetehpacketz/cisco-ip-trace#20]
Man I am really impressed with your coding skills and could not find anyone better to ask this. So, I am asking you a new request and it is not related to this code. BTW, your code is amazing. Now to my request, do you have a code that will login to cisco devices and take every command output that we specify in a separate file? For example, I will save a text file with the commands that I need to get output of, like show run, show cdp neigh and another file with the devices IP details. Once these details are fed to each file, running the code should log into each of these devices and take o/p of the command and each command output must be save in a separate file. Do you have one like that?

**Comment by routetehpacketz** [comment]
hey @technologyevangelist1,

I don't, but you could definitely sample from this and create it :)

If you are looking to just save the output of specific commands, though, I suggest looking at Ansible's collection for IOS:

https://galaxy.ansible.com/cisco/ios

**Comment by technologyevangelist1** [comment]
No worries. You may close this...Thanks again for all you are doing...
