### ISSUE TITLE
Remember if a neighbor can't be SSH'd into

### ISSUE THREAD

**Issue by hildebrau** [routetehpacketz/cisco-ip-trace#23]
Another feature request.  If for instance, it's tracing MAC's of a bunch of WiFi clients that are hanging off of a Cisco WLC, your script probably has no idea how to log into a WLC.  That or my it could just be that my authentication to the WLC is different than the switches.  Either way, I'd love if the script was intelligent enough to remember the CDP Neighbor IP(s) that it couldn't SSH into, and simply not try after the first failure on that same IP.  That could speed up the discovery of a long list of IPs, since it has to time out for 10 or so seconds each time.

Traced to CDP neighbor 10.10.10.15, but could not SSH into it.

Alternatively, you could add a command line argument for a regex that would compare the description of the local port to determine if it should even TRY to ssh to the CDP neighbor on that port.  In my case, I would add a regex to match /WLC|wlc/, so if the port description said WLC, it wouldn't bother w/ the nested/recursive SSH and just log what it knows and move on (which is what it does after ssh login fails on the WLC)

**Comment by routetehpacketz** [comment]
This was handled in #15. Simple handling of SSH failures is going to accommodate more scenarios than checking port descriptions. Keeping track of CDP neighbors that cannot be logged into is going to add overhead with minimal benefit than simply catching SSH failures as the script does now. I plan on adding multiprocessing to the script to increase overall performance.
