### ISSUE TITLE
port description with commas messes up the output csv

### ISSUE THREAD

**Issue by hildebrau** [routetehpacketz/cisco-ip-trace#24]
Should be an easy one, but you may want to strip out commas that you find in the interface descriptions.. otherwise it throws off the columns in the output CSV.

**Comment by routetehpacketz** [comment]
Hey @hildebrau,

Thanks for pointing this out. This should be simple enough to implement.

**Comment by routetehpacketz** [comment]
Hey @hildebrau,

May I trouble you to test [this copy](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/b221a3001d3636d970026b3207d70438d47c3cf8/cisco_ip_trace.py) against the issue you found with commas in port descriptions messing up the format of the output CSV file?

Thanks!

**Comment by routetehpacketz** [comment]
Corrected in #27
