### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by hildebrau** [routetehpacketz/cisco-ip-trace#25]
This would make a great docker container.  Has anyone made one for it that includes all the prereqs?

**Comment by routetehpacketz** [comment]
Hello @hildebrau,

There is no docker functionality intended for this script as it is not really an application. How would you expect the container to function differently than the flat Python file?

**Comment by hildebrau** [comment]
It could simply have all the dependencies built in with it. It was just an
idea.  Should be real simple for anyone familiar with setting up a
container from scratch.

**Comment by routetehpacketz** [comment]
I am going to close this as out of scope as it's not really intended functionality.
