### ISSUE TITLE
trunk_regex incorrectly matching

### ISSUE THREAD

**Issue by Zosodragonrouge** [routetehpacketz/cisco-ip-trace#29]
If the end port the device is on is a partial match for the trunk port on the switch there will be a false positive match in the `get_interface_mode` function that will return incorrect information for the "interface type", "VLANs on the port", and "Port MAC count".

ex:
`show interface trunk | inc Gi0/1` will show any trunk ports starting with `Gi0/1` so `Gi0/10-19` are potential matches

`Gi0/1` is the port the IP address I am tracing to resides on, and the device is host_b, if the trunk port on host_b is port `Gi0/11` this will make the `interface_trunk_match` function true and output incorrect data.

This is because of the regex `trunk_regex = re.compile(r'%s\s*(\S.*)' % mac_port, re.MULTILINE)` specifically the `\s*` is too inclusive.

In my own testing changing the regex to `trunk_regex = re.compile(r'%s\s+(\S.*)' % mac_port, re.MULTILINE)`, which is just changing the `\s*` to `\s+` has resolved this edge case and not yet produced any additional issues for me, since the regex `+` is requiring 1 or more of, as opposed to the `*` which is zero or more of.

Thank you for making this tool!

I can submit a pull request and subsequent merge request if that is the preferred method, but would like any others with potentially more diverse networks to test this out and see if it impacts them.

**Comment by routetehpacketz** [comment]
Hey @Zosodragonrouge!

Thanks for pointing out the error with that regex. If you want to create the pull request, I'll gladly review, test, and approve 😃

**Comment by routetehpacketz** [comment]
Corrected in #30
