### ISSUE TITLE
Request: Full ARP table scan

### ISSUE THREAD

**Issue by net9000** [routetehpacketz/cisco-ip-trace#7]
Great script but is there a way to tell the script to just look at the entire ARP table and look it all up?  And can you add a DNS lookup option to attempt to resolve IP to hostname?

**Comment by routetehpacketz** [comment]
hey @net9000! thank you for expressing interest in this script.

This "Issues" page is the most appropriate way of making feature requests on Github. I will edit this issue you have opened for the ARP table lookup feature request. can you open a new one for the DNS resolution request?

**Comment by routetehpacketz** [comment]
Hey again @net9000, I wanted to talk about this feature request in greater detail.

It seems to me that a more appropriate approach for this would be observing the connected subnets on a core switch/router and scanning each of those as this would account for devices currently on the network that the core device simply does not have an ARP entry for.

However, and please take no offense to this, I am a bit conflicted to implement this as it seems like a lazy approach to map things out on the network as opposed to scanning targeted IP ranges. 

For example, if you had 10 VLANs in your environment, wouldn't it be more efficient to run the script for each IP range and output a CSV for each?

Can you describe more of how you would use this functionality?

**Comment by net9000** [comment]
It depends really and no offense taken.  

Today I simply copy the ARP table, strip out the stuff I don't want then run a script against all the IPs it finds to spit out the host name and whether its alive (IE responds to ping).  This allows me to see everything on my network at a given time via a single script.  

At the end of the day I guess it just comes down to preference because I want to know what is currently on my network at any given time.  I don't need to scan every single CIDR within my environment because if there were devices on those the ARP table would have entries for them. 

In my mind its like I can do this one time or 30 times and I would prefer to do it once.  

Hopefully that makes sense.

**Comment by routetehpacketz** [comment]
thanks for replying so quickly. I think the way you have described it beckons to add this functionality. 

I am thinking the most appropriate way of allowing this method of running the script would be a unique command-line parameter like `trace.py -FULL -c [core IP]` or `-FA` or full ARP so that novice users do not run it inadvertently. what's your take on this?

**Comment by net9000** [comment]
Best to have options w/switches to allow the user to decide.  Let them
decide if they want to run for the ARP table, single IP or CIDR.  I see
advantages to running it multiple ways as long as the day coming out is the
same no matter what.

**Comment by net9000** [comment]
Another thought if you were able to implement this.  Is there a way to only return when it finds a match?  IE instead of NOT found just don't report anything for that IP/MAC address.  Would clean this up and only report relevant active data.  

```
10.192.16.40,Not Found
10.192.16.41,Not Found
10.192.16.42,Not Found
10.192.16.43,Not Found
10.192.16.44,Not Found
10.192.16.45,Not Found
10.192.16.46,Not Found
10.192.16.47,N/A,0017.6110.6f5f,sw6-2960-in,Gi1/0/36,,access,"16",1
10.192.16.48,Not Found
10.192.16.49,Not Found
10.192.16.50,Not Found
```

**Comment by routetehpacketz** [comment]
Hey @net9000,

Ya this should be no problem. I am hoping to have this turned around by this time next week.

**Comment by net9000** [comment]
@routetehpacketz any update to this?  This would be more beneficial to me than anything else.  Having to wait while it checks every IP in a /24 is painful.  I would never want to do this for a handful of /24s or 22 or 23s because of how long it takes.  It would be great if it could just reference the ARP table or a CSV of TXT file of IP addresses I want it to find and report back on.

**Comment by routetehpacketz** [comment]
Hey @net9000,

Sorry for the delay on this one. Once we confirm my updated copy is working for that other issue, at least just for Cisco IP phones, we can close that issue out and I can shift focus to this feature request.

**Comment by net9000** [comment]
@routetehpacketz 

Confirmed all is working.  This request would be the icing on the cake if it were able to glean IPs from the MAC table and only query/lookup those IPs.

**Comment by routetehpacketz** [comment]
@net9000 

just to confirm, you're expecting to dump the ARP table on the core and trace each IP, right?

**Comment by net9000** [comment]
> @net9000
> 
> just to confirm, you're expecting to dump the ARP table on the core and trace each IP, right?

Yes for anything with a MAC address found, IE anything that says INCOMPLETE skip those as they won't be found.  

```
Internet  10.102.16.1             -   8875.563d.3740  ARPA   Vlan16
Internet  10.102.16.5             3   b40c.2503.d800  ARPA   Vlan16
Internet  10.102.16.6             0   Incomplete      ARPA
Internet  10.102.16.7             0   Incomplete      ARPA
```

Or run the script and reference a txt or csv file with a list of IPs either manually created or gleaned from a ARP table.  

```
10.192.11.2
10.192.11.20
10.192.11.21
10.192.16.1
10.192.16.30
10.192.16.32
10.192.16.33
10.192.16.34
10.192.16.35
10.192.16.36
10.192.16.37
10.192.16.38
10.192.16.39
```

**Comment by routetehpacketz** [comment]
hey @net9000,

here is [my first attempt](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/66df7a888ae818ac9057a2ab7e30589f118f79e5/cisco_ip_trace.py) at adding full ARP scanning. it has to be run by issuing the command line argument `-FA` in addition to the other required args. the `-n` argument is not needed when using `-FA`.

please give it a try and let me know how it works.

**Comment by net9000** [comment]
@routetehpacketz 

Seemed to work just fine the first time I ran it.  Will run it some more to make sure.  This is the command I used which gave me exactly what I wanted. 

`:/local-dp$ sudo ./arp-v1.py -n 10.92.0.0/16 -FA -u admin -c 10.922.1.1 -f test-arp.csv`

Will follow up once I run it against some other devices.

**Comment by routetehpacketz** [comment]
hey @net9000,

that was my bad. I missed a piece when I moved my test copy to Pycharm. try [this one](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/2539a62a8ef529453387db52d424ad61f0a46a71/cisco_ip_trace.py)

**Comment by routetehpacketz** [comment]
@net9000 

it looks like the send_command_expect error you are getting is from the branch for pull request #16. the script uses netmiko's ability to detect the device's prompt to know when a command has finished (`Switch#` for example).

do you receive this every time you run this branch's latest version? if not, is there a reason you think the script isn't returning to the prompt on certain devices?

**Comment by net9000** [comment]
@routetehpacketz  no idea because, again, I haven't used it much as of late.

**Comment by routetehpacketz** [comment]
Closing this due to age. One complaint behind this request is how long it takes to process a single /24 network. In place of adding the option to simply scan the ARP table of the core router, I intend to greatly speed up the script through the use of Python's multiprocessing module.
