### ISSUE TITLE
Add DNS resolution? 

### ISSUE THREAD

**Issue by net9000** [routetehpacketz/cisco-ip-trace#8]
Would be nice to have the script attempt to resolve the IPs it finds and report back with the FQDNs.  That way you would have 99% of the identifying information for the IPs it does find in the ARP table.

**Comment by routetehpacketz** [comment]
Hey @net9000,

I am happy to inform you I have my first attempt at adding reverse DNS lookups to this script. I created a new branch and pull request for this, but you can get right to the [new script version here](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/218177c7deb58b784c57cb795ff625043deb0348/cisco_ip_trace.py).

Please do some testing and let me know what you think. Thanks!

**Comment by net9000** [comment]
Great!  I will try it out when I get a minute and report back.   Thanks for putting this together!

**Comment by net9000** [comment]
Having an issue with the script not having the enable pw, how and where can I add that?  

`  File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 18, in enable                                                      return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)                                                               File "/local-dp/p3-env/lib/python3.6/site-packages/netmiko/base_connection.py", line 1299, in enable                                                          raise ValueError(msg)                                                                                                                                   ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler. `

**Comment by routetehpacketz** [comment]
hey @net9000,

the script currently does not have any functionality to provide an enable password. I will have to add this as well. I am actually surprised it hasn't come up sooner. 

as I am fairly confident the DNS lookups are working, I am going to close this feature request and open a new one to add enable password handling.
